print("this is for initialization")
print("this is for second")
print("this is for second")
print("this is for second")
print("this is for second")
print("this is for second")
print("this is for second")
print("this is for second")
